services:

  docker-mysql:
    build:
      context: ./
      dockerfile: sql.Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=springboot_db
    ports:
      - 3307:3306  #HOST:CONTAINER

  app:
    build:
      context: ./
      dockerfile: app.Dockerfile
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/springboot_db?autoReconnect=true
    depends_on:
      - docker-mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
    - docker-mysql
