services:

  docker-mysql:
    build:
      context: ./
      dockerfile: sql.Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=springboot_db
    ports:
      - 3307:3306  #HOST:CONTAINER

  app:
    build:
      context: ./
      dockerfile: app.Dockerfile
    ports:
      - "8086:8086"
    environment:
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:  org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_NAME: springboot_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/${SPRING_DATASOURCE_NAME}?autoReconnect=true&createDatabaseIfNotExist=true
    depends_on:
      - docker-mysql
