databases:
  - name: postgresql
    region: frankfurt
    plan: free

envVarGroups:
- name: mysql
  envVars:
  - key: MYSQL_DATABASE
    value: springboot_db
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true

services:
  - type: pserv
    name: mysql
    plan: free
    dockerfilePath: ./sql.Dockerfile
    runtime: docker
    autoDeploy: false
    disk:
      name: mysql
      mountPath: /var/lib/mysql
      sizeGB: 1
    envVars:
    - fromGroup: mysql

  - type: web
    name: fast-cash
    runtime: docker
    region: frankfurt
    plan: free
    healthCheckPath: /
    dockerfilePath: ./app.Dockerfile
    envVars:
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_DATASOURCE_CONNECTION_STRING
        fromDatabase:
          name: postgresql
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: postgresql
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: postgresql
          property: password
      - key: SPRING_DATASOURCE_HOST
        fromDatabase:
          name: postgresql
          property: host
      - key: SPRING_DATASOURCE_PORT
        fromDatabase:
          name: postgresql
          property: port
      - key: SPRING_DATASOURCE_NAME
        fromDatabase:
          name: postgresql
          property: database
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_NAME}