services:

  - type: web  # Since Render doesn't have a direct "service" type for arbitrary containers, use "web"
    name: mysql
    runtime: docker
    dockerfilePath: ./sql.Dockerfile  # Path to your custom Dockerfile
    region: frankfurt
    plan: free
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root
      - key: MYSQL_DATABASE
        value: springboot_db

  - type: web
    name: springboot-app
    runtime: docker
    dockerfilePath: ./app.Dockerfile
    region: frankfurt
    plan: free
    healthCheckPath: /
    envVars:
      # - key: SPRING_DATASOURCE_USERNAME
        # value: root
        # fromService: # Reference a property from another service
        #   type: web
        #   name: mysql
        #   property: user
      - key: SPRING_DATASOURCE_PASSWORD
        value: root
        # fromService:
        #   type: web
        #   name: mysql
        #   property: password
      - key: SPRING_DATASOURCE_HOST
        fromService:
          type: web
          name: mysql
          property: host
      - key: SPRING_DATASOURCE_PORT
        fromService:
          type: web
          name: mysql
          property: port
      # - key: SPRING_DATASOURCE_SCHEMA
      #   fromService:
      #     type: web
      #     name: mysql
      #     property: database
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/springboot_db?autoReconnect=true&createDatabaseIfNotExist=true         