databases:
  - name: postgresql
    region: frankfurt
    plan: free
    ipAllowList: # required
      - source: 0.0.0.0/0
        description: everywhere

services:
  - type: web
    name: fast-cash
    runtime: docker
    region: frankfurt
    plan: free
    healthCheckPath: /
    dockerfilePath: ./web.Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_CONNECTION_STRING
        fromDatabase:
          name: postgresql
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: postgresql
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: postgresql
          property: password
      - key: SPRING_DATASOURCE_HOST
        fromDatabase:
          name: postgresql
          property: host
      - key: SPRING_DATASOURCE_PORT
        fromDatabase:
          name: postgresql
          property: port
      - key: SPRING_DATASOURCE_SCHEMA
        fromDatabase:
          name: postgresql
          property: database
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_SCHEMA}