services:
  - type: web  # Since Render doesn't have a direct "service" type for arbitrary containers, use "web"
    name: mysql
    runtime: docker
    dockerfilePath: ./sql.Dockerfile  # Path to your custom Dockerfile
    region: frankfurt
    plan: free
    envVars:
      # - key: PORT
      #   value: 3036  # Expose the MySQL port internally
      - key: MYSQL_ROOT_PASSWORD
        value: root
      - key: MYSQL_DATABASE
        value: springboot_db

  - type: web
    name: springboot-app
    runtime: docker
    dockerfilePath: ./app.Dockerfile
    region: frankfurt
    plan: free
    healthCheckPath: /
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/springboot_db?autoReconnect=true

      - key: MYSQL_HOST
        fromService: # Reference a property from another service (see available properties below)
          type: web
          name: mysql
          property: host
      - key: MYSQL_PORT
        fromService:
          type: web
          name: mysql
          property: port
          
      - key: PORT
        value: 10000  # Expose the port the app runs on