name: Java CI with Maven & NPM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Super-Linter
      uses: super-linter/super-linter@v7.1.0
